# Generated by Django 4.1.10 on 2023-08-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_conversation_alter_subcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
